function R = eul2rotm_func(in1)
%EUL2ROTM_FUNC
%    R = EUL2ROTM_FUNC(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    13-Apr-2023 21:19:20

theta1 = in1(1,:);
theta2 = in1(2,:);
theta3 = in1(3,:);
t2 = cos(theta1);
t3 = cos(theta2);
t4 = cos(theta3);
t5 = sin(theta1);
t6 = sin(theta2);
t7 = sin(theta3);
R = reshape([t3.*t4,t2.*t7+t4.*t5.*t6,t5.*t7-t2.*t4.*t6,-t3.*t7,t2.*t4-t5.*t6.*t7,t4.*t5+t2.*t6.*t7,t6,-t3.*t5,t2.*t3],[3,3]);
